title: PMLi
description: Esta documentação é do projeto PMLi
theme: just-the-docs
url: https://hugocorreia77.github.io/doc-test/

collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  architecture:
    permalink: "/:collection/:path/"
    output: true
  concepts:
    permalink: "/:collection/:path/"
    output: true
  functional:
    permalink: "/:collection/:path/"
    output: true


just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    architecture:
      name: Arquitetura
    concepts:
      name: Conceitos
    functional:
      name: Funcional
