title: PMLi
description: Esta documentação é do projeto PMLi
theme: just-the-docs
url: https://hugocorreia77.github.io/doc-test/

footer_content: "Copyright &copy; 2025 Sonae - MCDigital"

last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p" 

gh_edit_link: true 
gh_edit_link_text: "Editar a página no GitHub."
gh_edit_repository: "https://github.com/sonaemc-instore/pml-fw-docs" 

sass:
  style: compressed
  custom_css: assets/css/custom.css
