title: PMLi
description: Esta documentação é do projeto PMLi
theme: just-the-docs
url: https://sonaemc-instore.github.io/pml-fw-docs

collections:
  architecture:
    permalink: "/:collection/:path/"
    output: true
 
just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    architecture:
      name: Arquitetura
 
